name: portfolio
description: A new Flutter project.

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_speed_dial: ^4.3.0
  random_string: ^2.3.1
  fluttertoast: ^8.2.2
  google_fonts: ^4.0.4
  floating_bottom_navigation_bar: ^1.5.2
  cupertino_icons: ^1.0.2
  font_awesome_flutter: ^10.3.0
  google_nav_bar: ^5.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true
  assets:
    - assets/
  #   - images/a_dot_ham.jpeg

